
DROP TABLE ORDER_PAYMENT CASCADE CONSTRAINTS;
DROP TABLE TRANSACTION_FINAL CASCADE CONSTRAINTS;
DROP TABLE MOVIE_INFO CASCADE CONSTRAINTS;
DROP TABLE ORDER_FINAL CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE MOVIE CASCADE CONSTRAINTS;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
