INSERT INTO CUSTOMER VALUES (1, 'Amal', 'Pramod', 'amal@mail.com', '12 Maple St', '4161111111', 50);
INSERT INTO CUSTOMER VALUES (2, 'John', 'Smith', 'johnsmith@gmail.com', '22 Lakeview Rd', '4162222222', 120);
INSERT INTO CUSTOMER VALUES (3, 'Sarah', 'Lee', 'sarahlee@yahoo.com', '99 Rose Ave', '6473333333', 200);
INSERT INTO CUSTOMER VALUES (4, 'David', 'Kim', 'davidk@gmail.com', '77 Bay St', '4374444444', 10);
INSERT INTO CUSTOMER VALUES (5, 'Maya', 'Patel', 'patelmaya@mail.com', '5 Oakwood Blvd', '4165555555', 88);
INSERT INTO CUSTOMER VALUES (6, 'Ravi', 'Singh', 'ravi.singh@gmail.com', '34 Finch Ave', '6476666666', 75);
INSERT INTO CUSTOMER VALUES (7, 'Emily', 'Johnson', 'emjay@mail.com', '250 Queen St', '4167777777', 30);
INSERT INTO CUSTOMER VALUES (8, 'Carlos', 'Hernandez', 'carlos.h@gmail.com', '430 Dundas St', '6478888888', 56);
INSERT INTO CUSTOMER VALUES (9, 'Aisha', 'Khan', 'aishakhan@hotmail.com', '89 Weston Rd', '4169999999', 150);
INSERT INTO CUSTOMER VALUES (10, 'Liam', 'Anderson', 'liam.anderson@mail.com', '14 Bloor St', '4370000000', 300);

INSERT INTO MOVIE VALUES (1, 'Inception', 'Christopher Nolan', 'Sci-Fi', 'English', 2010);
INSERT INTO MOVIE VALUES (2, 'Interstellar', 'Christopher Nolan', 'Sci-Fi', 'English', 2014);
INSERT INTO MOVIE VALUES (3, 'Parasite', 'Bong Joon-ho', 'Thriller', 'Korean', 2019);
INSERT INTO MOVIE VALUES (4, 'The Dark Knight', 'Christopher Nolan', 'Action', 'English', 2008);
INSERT INTO MOVIE VALUES (5, 'Joker', 'Todd Phillips', 'Crime', 'English', 2019);
INSERT INTO MOVIE VALUES (6, 'Avatar', 'James Cameron', 'Sci-Fi', 'English', 2009);
INSERT INTO MOVIE VALUES (7, 'The Matrix', 'Wachowski Sisters', 'Sci-Fi', 'English', 1999);
INSERT INTO MOVIE VALUES (8, 'Coco', 'Lee Unkrich', 'Animation', 'English', 2017);
INSERT INTO MOVIE VALUES (9, 'Dune', 'Denis Villeneuve', 'Sci-Fi', 'English', 2021);
INSERT INTO MOVIE VALUES (10, 'Whiplash', 'Damien Chazelle', 'Drama', 'English', 2014);

INSERT INTO MOVIE_INFO VALUES (1, 'Inception', 'Sci-Fi');
INSERT INTO MOVIE_INFO VALUES (2, 'Interstellar', 'Sci-Fi');
INSERT INTO MOVIE_INFO VALUES (3, 'Parasite', 'Thriller');
INSERT INTO MOVIE_INFO VALUES (4, 'The Dark Knight', 'Action');
INSERT INTO MOVIE_INFO VALUES (5, 'Joker', 'Crime');
INSERT INTO MOVIE_INFO VALUES (6, 'Avatar', 'Sci-Fi');
INSERT INTO MOVIE_INFO VALUES (7, 'The Matrix', 'Sci-Fi');
INSERT INTO MOVIE_INFO VALUES (8, 'Coco', 'Animation');
INSERT INTO MOVIE_INFO VALUES (9, 'Dune', 'Sci-Fi');
INSERT INTO MOVIE_INFO VALUES (10, 'Whiplash', 'Drama');

INSERT INTO ORDER_FINAL VALUES (101, 1, 2, 19.99);
INSERT INTO ORDER_FINAL VALUES (102, 2, 1, 14.50);
INSERT INTO ORDER_FINAL VALUES (103, 3, 3, 12.00);
INSERT INTO ORDER_FINAL VALUES (104, 4, 1, 11.99);
INSERT INTO ORDER_FINAL VALUES (105, 5, 2, 10.99);
INSERT INTO ORDER_FINAL VALUES (106, 6, 1, 15.00);
INSERT INTO ORDER_FINAL VALUES (107, 7, 4, 9.99);
INSERT INTO ORDER_FINAL VALUES (108, 8, 1, 8.99);
INSERT INTO ORDER_FINAL VALUES (109, 9, 2, 16.00);
INSERT INTO ORDER_FINAL VALUES (110, 10, 1, 17.49);

INSERT INTO ORDER_PAYMENT VALUES (101, 39.98, 'Credit Card');
INSERT INTO ORDER_PAYMENT VALUES (102, 14.50, 'PayPal');
INSERT INTO ORDER_PAYMENT VALUES (103, 36.00, 'Debit Card');
INSERT INTO ORDER_PAYMENT VALUES (104, 11.99, 'Credit Card');
INSERT INTO ORDER_PAYMENT VALUES (105, 21.98, 'Google Pay');
INSERT INTO ORDER_PAYMENT VALUES (106, 15.00, 'Credit Card');
INSERT INTO ORDER_PAYMENT VALUES (107, 39.96, 'Credit Card');
INSERT INTO ORDER_PAYMENT VALUES (108, 8.99, 'Cash');
INSERT INTO ORDER_PAYMENT VALUES (109, 32.00, 'Debit');
INSERT INTO ORDER_PAYMENT VALUES (110, 17.49, 'Credit Card');

INSERT INTO TRANSACTION_FINAL VALUES (201, 101, SYSDATE, 'PAID');
INSERT INTO TRANSACTION_FINAL VALUES (202, 102, SYSDATE, 'PAID');
INSERT INTO TRANSACTION_FINAL VALUES (203, 103, SYSDATE, 'PENDING');
INSERT INTO TRANSACTION_FINAL VALUES (204, 104, SYSDATE, 'PAID');
INSERT INTO TRANSACTION_FINAL VALUES (205, 105, SYSDATE, 'FAILED');
INSERT INTO TRANSACTION_FINAL VALUES (206, 106, SYSDATE, 'PAID');
INSERT INTO TRANSACTION_FINAL VALUES (207, 107, SYSDATE, 'PAID');
INSERT INTO TRANSACTION_FINAL VALUES (208, 108, SYSDATE, 'PAID');
INSERT INTO TRANSACTION_FINAL VALUES (209, 109, SYSDATE, 'PENDING');
INSERT INTO TRANSACTION_FINAL VALUES (210, 110, SYSDATE, 'PAID');

INSERT INTO REVIEW VALUES (301, 5, 'Mind-blowing visuals!', SYSDATE, 1, 1);
INSERT INTO REVIEW VALUES (302, 4, 'Very emotional.', SYSDATE, 2, 3);
INSERT INTO REVIEW VALUES (303, 3, 'Good but confusing.', SYSDATE, 1, 4);
INSERT INTO REVIEW VALUES (304, 5, 'Masterpiece.', SYSDATE, 4, 2);
INSERT INTO REVIEW VALUES (305, 2, 'Not my style.', SYSDATE, 5, 5);
INSERT INTO REVIEW VALUES (306, 4, 'Amazing worldbuilding.', SYSDATE, 9, 6);
INSERT INTO REVIEW VALUES (307, 5, 'Loved every minute.', SYSDATE, 8, 7);
INSERT INTO REVIEW VALUES (308, 3, 'Average.', SYSDATE, 10, 8);
INSERT INTO REVIEW VALUES (309, 5, 'Incredible score.', SYSDATE, 10, 10);
INSERT INTO REVIEW VALUES (310, 4, 'Very entertaining.', SYSDATE, 7, 9);

